### ISSUE TITLE
PHP 7 Compatibility Errors

### ISSUE THREAD

**Issue by ERTurner** [cosmocode/explain#4]
I receive the following errors when installing the plugin:
- Warning: Declaration of syntax_plugin_explain::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\explain\syntax.php on line 132
- Warning: Declaration of syntax_plugin_explain::render($format, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\explain\syntax.php on line 132

**Comment by splitbrain** [comment]
fixed with #5
